#!/usr/bin/env node
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { after, test } from 'node:test';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isValidVersion, main, updateCargoLockPackageVersion } from '../sync-version.mjs';

const TEST_FILE = fileURLToPath(import.meta.url);
const SYNC_SCRIPT = join(dirname(TEST_FILE), '..', 'sync-version.mjs');

function writeFixtureFile(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function createFixtureRepo() {
  const root = mkdtempSync(join(tmpdir(), 'pinvou-sync-version-'));
  writeFixtureFile(root, 'VERSION', '0.8.9\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/tauri.conf.json', '{"version":"0.8.9"}\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/Cargo.toml', '[package]\nname = "pinvou3-tauri"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou-knowledge/Cargo.toml', '[package]\nname = "pinvou-knowledge"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou-knowledge/Cargo.lock', '[[package]]\nname = "pinvou-knowledge"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/Cargo.lock', `[[package]]
name = "dependency"
version = "1.0.0"

[[package]]
name = "pinvou-knowledge"
version = "0.8.8"

[[package]]
name = "pinvou3-tauri"
version = "0.8.8"
`);
  writeFixtureFile(root, 'pinvou3-app/package.json', '{"version":"0.8.9"}\n');
  writeFixtureFile(root, 'pinvou-cli/Cargo.lock', `[[package]]
name = "pinvou-knowledge"
version = "0.8.8"

[[package]]
name = "pinvou3-tauri"
version = "0.8.8"
`);
  writeFixtureFile(root, 'scripts/.gitkeep', '');
  copyFileSync(SYNC_SCRIPT, join(root, 'scripts/sync-version.mjs'));
  return root;
}

function runFixtureScript(root, args = []) {
  return spawnSync(process.execPath, [join(root, 'scripts/sync-version.mjs'), ...args], {
    cwd: root,
    encoding: 'utf8',
  });
}

test('接受合法 SemVer 版本号', () => {
  for (const version of [
    '0.0.0',
    '0.6.5',
    '1.2.3-rc.1',
    '1.2.3-alpha.beta',
    '1.2.3+build.01',
    '1.2.3-rc.1+build.7',
  ]) {
    assert.equal(isValidVersion(version), true, version);
  }
});

test('拒绝会导致 Cargo 或打包阶段失败的非法版本号', () => {
  for (const version of [
    '1.2',
    'v1.2.3',
    '01.2.3',
    '1.02.3',
    '1.2.03',
    '1.2.3foo',
    '1.2.3-',
    '1.2.3-01',
    '1.2.3..',
    '1.2.3+',
  ]) {
    assert.equal(isValidVersion(version), false, version);
  }
});

test('只同步独立 Cargo.lock 中 pinvou-knowledge 自身的版本', () => {
  const lock = `# generated
[[package]]
name = "dependency"
version = "0.8.1"

[[package]]
name = "pinvou-knowledge"
version = "0.8.1"
dependencies = ["dependency"]
`;

  const result = updateCargoLockPackageVersion(lock, 'pinvou-knowledge', '0.8.3');

  assert.equal(result.version, '0.8.1');
  assert.match(result.content, /name = "dependency"\nversion = "0\.8\.1"/u);
  assert.match(result.content, /name = "pinvou-knowledge"\nversion = "0\.8\.3"/u);
});

test('Cargo.lock 缺少或重复根包时拒绝静默通过', () => {
  assert.throws(
    () => updateCargoLockPackageVersion('[[package]]\nname = "other"\nversion = "1.0.0"\n', 'pinvou-knowledge'),
    /实际找到 0 个/u,
  );
  const duplicate = `${'[[package]]\nname = "pinvou-knowledge"\nversion = "0.8.1"\n\n'.repeat(2)}`;
  assert.throws(
    () => updateCargoLockPackageVersion(duplicate, 'pinvou-knowledge'),
    /实际找到 2 个/u,
  );
});

// ---- main() full sync/validate: runs in a temp-dir sandbox, never touching the real repository ----

const TARGET_VERSION = '0.8.8';
const OLD_VERSION = '0.8.7';

// The real shape of src-tauri/Cargo.lock: one [[package]] section each for this crate and the path dependency pinvou-knowledge
function srcTauriLock(tauriVersion, knowledgeVersion) {
  return `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "pinvou-knowledge"
version = "${knowledgeVersion}"

[[package]]
name = "pinvou3-tauri"
version = "${tauriVersion}"
dependencies = [
 "pinvou-knowledge",
]
`;
}

function knowledgeLock(version) {
  return `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.210"

[[package]]
name = "pinvou-knowledge"
version = "${version}"
dependencies = [
 "serde",
]
`;
}

// The real shape of pinvou-cli/Cargo.lock: the standalone workspace vendors both
// release crates as path dependencies, one [[package]] section each.
function cliLock(tauriVersion, knowledgeVersion) {
  return `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "pinvou-knowledge"
version = "${knowledgeVersion}"

[[package]]
name = "pinvou3-tauri"
version = "${tauriVersion}"
dependencies = [
 "pinvou-knowledge",
]
`;
}

const sandboxRoots = [];
after(() => {
  for (const root of sandboxRoots) {
    rmSync(root, { recursive: true, force: true });
  }
});

function createSandboxRoot() {
  const root = mkdtempSync(join(tmpdir(), 'pinvou-sync-version-'));
  sandboxRoots.push(root);
  mkdirSync(join(root, 'pinvou3-app/src-tauri'), { recursive: true });
  mkdirSync(join(root, 'pinvou-knowledge'), { recursive: true });
  mkdirSync(join(root, 'pinvou-cli'), { recursive: true });
  // VERSION is the single source of truth, already bumped to the target version; the other files stay at the old version, waiting to be synced
  writeFileSync(join(root, 'VERSION'), `${TARGET_VERSION}\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/tauri.conf.json'), `${JSON.stringify({ version: OLD_VERSION }, null, 2)}\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.toml'), `[package]\nname = "pinvou3-tauri"\nversion = "${OLD_VERSION}"\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.lock'), srcTauriLock(OLD_VERSION, OLD_VERSION));
  writeFileSync(join(root, 'pinvou-knowledge/Cargo.toml'), `[package]\nname = "pinvou-knowledge"\nversion = "${OLD_VERSION}"\n`);
  writeFileSync(join(root, 'pinvou-knowledge/Cargo.lock'), knowledgeLock(OLD_VERSION));
  writeFileSync(join(root, 'pinvou-cli/Cargo.lock'), cliLock(OLD_VERSION, OLD_VERSION));
  writeFileSync(join(root, 'pinvou3-app/package.json'), `${JSON.stringify({ name: 'pinvou3-app', version: OLD_VERSION }, null, 2)}\n`);
  return root;
}

function readSandboxVersions(root) {
  const srcTauriLockContent = readFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.lock'), 'utf8');
  const cliLockContent = readFileSync(join(root, 'pinvou-cli/Cargo.lock'), 'utf8');
  return {
    tauriConf: JSON.parse(readFileSync(join(root, 'pinvou3-app/src-tauri/tauri.conf.json'), 'utf8')).version,
    cargoToml: readFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.toml'), 'utf8'),
    srcTauriTauri: updateCargoLockPackageVersion(srcTauriLockContent, 'pinvou3-tauri').version,
    srcTauriKnowledge: updateCargoLockPackageVersion(srcTauriLockContent, 'pinvou-knowledge').version,
    cliTauri: updateCargoLockPackageVersion(cliLockContent, 'pinvou3-tauri').version,
    cliKnowledge: updateCargoLockPackageVersion(cliLockContent, 'pinvou-knowledge').version,
    knowledgeLock: updateCargoLockPackageVersion(readFileSync(join(root, 'pinvou-knowledge/Cargo.lock'), 'utf8'), 'pinvou-knowledge').version,
    packageJson: JSON.parse(readFileSync(join(root, 'pinvou3-app/package.json'), 'utf8')).version,
  };
}

test('sync mode updates all targets, including both src-tauri Cargo.lock packages', () => {
  const root = createSandboxRoot();

  assert.equal(main(root), 0);

  const versions = readSandboxVersions(root);
  assert.equal(versions.tauriConf, TARGET_VERSION);
  assert.match(versions.cargoToml, /version = "0\.8\.8"/u);
  assert.equal(versions.srcTauriTauri, TARGET_VERSION);
  assert.equal(versions.srcTauriKnowledge, TARGET_VERSION);
  assert.equal(versions.cliTauri, TARGET_VERSION);
  assert.equal(versions.cliKnowledge, TARGET_VERSION);
  assert.equal(versions.knowledgeLock, TARGET_VERSION);
  assert.equal(versions.packageJson, TARGET_VERSION);
});

test('--check passes and stays read-only when everything is consistent', () => {
  const root = createSandboxRoot();
  assert.equal(main(root), 0);
  const before = readSandboxVersions(root);

  assert.equal(main(root, { checkOnly: true }), 0);

  const after = readSandboxVersions(root);
  assert.deepEqual(after, before);
  assert.equal(after.srcTauriTauri, TARGET_VERSION);
  assert.equal(after.srcTauriKnowledge, TARGET_VERSION);
  assert.equal(after.cliTauri, TARGET_VERSION);
  assert.equal(after.cliKnowledge, TARGET_VERSION);
});

test('--check fails when src-tauri Cargo.lock lags one version behind (real regression scenario)', () => {
  for (const packageName of ['pinvou3-tauri', 'pinvou-knowledge']) {
    const root = createSandboxRoot();
    assert.equal(main(root), 0);

    // Reproduce the regression: one package version missed in src-tauri's Cargo.lock
    const lockPath = join(root, 'pinvou3-app/src-tauri/Cargo.lock');
    const result = updateCargoLockPackageVersion(readFileSync(lockPath, 'utf8'), packageName, OLD_VERSION);
    writeFileSync(lockPath, result.content);
    const before = readSandboxVersions(root);

    assert.equal(main(root, { checkOnly: true }), 1, packageName);
    // --check is read-only: apart from the manually constructed rollback, no other file may change
    const after = readSandboxVersions(root);
    assert.equal(after.srcTauriTauri, before.srcTauriTauri, packageName);
    assert.equal(after.srcTauriKnowledge, before.srcTauriKnowledge, packageName);
    assert.equal(after.knowledgeLock, TARGET_VERSION, packageName);
  }
});

test('--check fails when pinvou-cli Cargo.lock lags behind (the #415 drift scenario)', () => {
  for (const packageName of ['pinvou3-tauri', 'pinvou-knowledge']) {
    const root = createSandboxRoot();
    assert.equal(main(root), 0);

    // Reproduce the regression: one package version missed in pinvou-cli's Cargo.lock
    const lockPath = join(root, 'pinvou-cli/Cargo.lock');
    const result = updateCargoLockPackageVersion(readFileSync(lockPath, 'utf8'), packageName, OLD_VERSION);
    writeFileSync(lockPath, result.content);

    assert.equal(main(root, { checkOnly: true }), 1, packageName);
    // --check is read-only: the manually constructed rollback must survive unchanged
    assert.equal(
      updateCargoLockPackageVersion(readFileSync(lockPath, 'utf8'), packageName).version,
      OLD_VERSION,
      packageName,
    );
  }
});

test('src-tauri Cargo.lock has exactly one section per package, updatable independently', () => {
  const lock = srcTauriLock(OLD_VERSION, OLD_VERSION);

  const tauriResult = updateCargoLockPackageVersion(lock, 'pinvou3-tauri', TARGET_VERSION);
  assert.equal(tauriResult.version, OLD_VERSION);
  assert.match(tauriResult.content, /name = "pinvou3-tauri"\nversion = "0\.8\.8"/u);
  assert.match(tauriResult.content, /name = "pinvou-knowledge"\nversion = "0\.8\.7"/u);

  const knowledgeResult = updateCargoLockPackageVersion(tauriResult.content, 'pinvou-knowledge', TARGET_VERSION);
  assert.equal(knowledgeResult.version, OLD_VERSION);
  assert.match(knowledgeResult.content, /name = "pinvou3-tauri"\nversion = "0\.8\.8"/u);
  assert.match(knowledgeResult.content, /name = "pinvou-knowledge"\nversion = "0\.8\.8"/u);
});

test('missing or duplicated packages in src-tauri Cargo.lock are rejected, not silently accepted', () => {
  // The Chinese regex anchors below match sync-version.mjs's pre-existing
  // (history-exempt) error text and must stay in sync with that message.
  assert.throws(
    () => updateCargoLockPackageVersion('[[package]]\nname = "serde"\nversion = "1.0.0"\n', 'pinvou3-tauri'),
    /实际找到 0 个/u,
  );
  const duplicate = srcTauriLock(OLD_VERSION, OLD_VERSION) + '[[package]]\nname = "pinvou3-tauri"\nversion = "0.8.7"\n';
  assert.throws(
    () => updateCargoLockPackageVersion(duplicate, 'pinvou3-tauri'),
    /实际找到 2 个/u,
  );
});

test('write mode updates both workspace packages in the application Cargo.lock', (t) => {
  const root = createFixtureRepo();
  t.after(() => rmSync(root, { recursive: true, force: true }));

  const result = runFixtureScript(root);
  assert.equal(result.status, 0, result.stderr);

  const lock = readFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.lock'), 'utf8');
  assert.match(lock, /name = "pinvou-knowledge"\nversion = "0\.8\.9"/u);
  assert.match(lock, /name = "pinvou3-tauri"\nversion = "0\.8\.9"/u);
  assert.match(lock, /name = "dependency"\nversion = "1\.0\.0"/u);
});

test('write mode updates both workspace packages in the pinvou-cli Cargo.lock', (t) => {
  const root = createFixtureRepo();
  t.after(() => rmSync(root, { recursive: true, force: true }));

  const result = runFixtureScript(root);
  assert.equal(result.status, 0, result.stderr);

  const lock = readFileSync(join(root, 'pinvou-cli/Cargo.lock'), 'utf8');
  assert.match(lock, /name = "pinvou-knowledge"\nversion = "0\.8\.9"/u);
  assert.match(lock, /name = "pinvou3-tauri"\nversion = "0\.8\.9"/u);
});

test('--check rejects version drift in either pinvou-cli Cargo.lock workspace package', (t) => {
  for (const driftingPackageName of ['pinvou-knowledge', 'pinvou3-tauri']) {
    const root = createFixtureRepo();
    t.after(() => rmSync(root, { recursive: true, force: true }));
    const syncResult = runFixtureScript(root);
    assert.equal(syncResult.status, 0, syncResult.stderr);

    const lockPath = join(root, 'pinvou-cli/Cargo.lock');
    const lock = readFileSync(lockPath, 'utf8').replace(
      new RegExp(`(name = "${driftingPackageName}"\\nversion = ")0\\.8\\.9"`, 'u'),
      (_match, prefix) => `${prefix}0.8.8"`,
    );
    writeFileSync(lockPath, lock);

    const result = runFixtureScript(root, ['--check']);
    assert.equal(result.status, 1, `${driftingPackageName}: ${result.stdout}\n${result.stderr}`);
    assert.match(result.stderr, /pinvou-cli\/Cargo\.lock/u);
  }
});

test('--check rejects version drift in either application Cargo.lock workspace package', (t) => {
  for (const driftingPackageName of ['pinvou-knowledge', 'pinvou3-tauri']) {
    const root = createFixtureRepo();
    t.after(() => rmSync(root, { recursive: true, force: true }));
    const syncResult = runFixtureScript(root);
    assert.equal(syncResult.status, 0, syncResult.stderr);

    const lockPath = join(root, 'pinvou3-app/src-tauri/Cargo.lock');
    const lock = readFileSync(lockPath, 'utf8').replace(
      new RegExp(`(name = "${driftingPackageName}"\\nversion = ")0\\.8\\.9"`, 'u'),
      (_match, prefix) => `${prefix}0.8.8"`,
    );
    writeFileSync(lockPath, lock);

    const result = runFixtureScript(root, ['--check']);
    assert.equal(result.status, 1, `${driftingPackageName}: ${result.stdout}\n${result.stderr}`);
    assert.match(result.stderr, /pinvou3-app\/src-tauri\/Cargo\.lock/u);
  }
});

test('missing lock package entry exits 2 with a clean message instead of an uncaught stack trace', (t) => {
  const root = createFixtureRepo();
  t.after(() => rmSync(root, { recursive: true, force: true }));

  // Drop the pinvou3-tauri section so the lock lookup finds zero matches.
  const lockPath = join(root, 'pinvou3-app/src-tauri/Cargo.lock');
  const lock = readFileSync(lockPath, 'utf8').replace(
    /\n\[\[package\]\]\nname = "pinvou3-tauri"\nversion = "0\.8\.8"\n/u,
    '\n',
  );
  writeFileSync(lockPath, lock);

  const result = runFixtureScript(root, ['--check']);
  assert.equal(result.status, 2, `${result.stdout}\n${result.stderr}`);
  // The Chinese anchor matches sync-version.mjs's pre-existing (history-exempt) error text.
  assert.match(result.stderr, /实际找到 0 个/u);
  assert.doesNotMatch(result.stderr, /^\s+at\s/um);
});
