[package]
name = "pinvou-product-backend"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
agent-backend-api = { path = "../agent-backend-api" }
anyhow = "1.0"
pinvou3-lib = { package = "pinvou3-tauri", path = "../../../pinvou3-app/src-tauri", default-features = false, features = ["benchmark-hooks", "local-embed"] }
